"""
This code demonstrates how to use the ChatGroq model from the langchain_groq library to 
create a simple chatbot that can answer questions. It uses a chat prompt template to 
structure the conversation and a string output parser to extract the text response from 
the model. The OpenAI API key is loaded from an environment variable using the dotenv 
library.
Load API key
LLM defined with llama as model and groq as provider
Prompt defined
Parser defined
Chain -> Prompt1 | LLM | Parser
Response generated by invoking the chain with an input question
"""

from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from dotenv import load_dotenv
import os

load_dotenv()

llm = ChatGroq(
    api_key=os.getenv("OPENAI_API_KEY"),
    model="llama-3.1-8b-instant"
)

prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a helpful assistant."),
    ("user", "{input}")
])

parser = StrOutputParser()

# StrOutputParser extracts just the text so you don't need .content anymore
chain = prompt | llm | parser

response = chain.invoke({"input": "What is photosynthesis?"})
print(response)